#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

DOKKU_ROOT=${DOKKU_ROOT:-/home/dokku}
CACHE_DIR="$DOKKU_ROOT/.cache"

case "$1" in
  forego:update)
    update_forego $CACHE_DIR/forego
    ;;

  forego:version)
    echo -n "forego version: "
    if [ -e $CACHE_DIR/forego ]; then
        $CACHE_DIR/forego version
    else
        echo "forego binary not found in $CACHE_DIR/"
        echo "You can run forego:update or re-release any container to install the latest forego binary."
    fi
    ;;

  help)
    cat && cat<<EOF
    forego:update                                   Update the forego binary. Changes take effect in containers on the next release.
    forego:version                                  Show the forego binary version
EOF
  ;;

esac
