#!/bin/bash

APP="$1"
IMAGE="dokku/$APP"
DOKKU_ROOT=${DOKKU_ROOT:-/home/dokku}
CACHE_DIR="$DOKKU_ROOT/.cache"

# Check for Procfile
id=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $id) -ne 0  ]; then
  exit 0
fi

echo "-----> dokku-forego"

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

echo "-----> Fetching forego binary..."
# Create the cache directory if it doesn't exist
[ ! -d $CACHE_DIR ] && mkdir -p $CACHE_DIR
FOREGO_BIN="$CACHE_DIR/forego"
fetch_forego $FOREGO_BIN
copy_to_container "$FOREGO_BIN" /app/vendor/forego/bin/forego 755
echo "       Done"

echo "-----> Injecting forego runner..."
id=$(cat "$PLUGIN_DIR/lib/runner" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /start")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "       Done"
