#!/bin/bash

# This script replaces /start in the container.
# It is copied over /start in the 'post-release' hook script.

export HOME=/app
username=$(egrep "^u[1-9]+" /etc/passwd 2> /dev/null | awk -F':' '{ print $1 }')
chown -R "$username":"$username" /app
cd /app

for file in .profile.d/*.sh; do
  source "$file"
done

rm -f .env
for file in $(find .profile.d -name '0*.sh'); do
  cat "$file" >> .env
done

hash -r

case "$(basename $0)" in
  start)
    command="$HOME/vendor/forego/bin/forego start $1 -r"
    ;;
  *)
    command="$@"
    ;;
esac
setuidgid $username $(eval echo ${command})
